version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:latest

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - FRONTEND_IMAGE=frontend:latest
    image: backend:latest
    ports:
      - "5000:5000"
    environment:
      - VIDEO_DEVICE=${VIDEO_DEVICE}
    devices:
      - "${VIDEO_DEVICE}:${VIDEO_DEVICE}"
