version: "3.9"
services:
  backend:
    build:
      context: ./app
      dockerfile: backend/Dockerfile
    image: backend:latest
    ports:
      - "5000:5000"
    environment:
      - VIDEO_DEVICE=${VIDEO_DEVICE}
    devices:
      - "${VIDEO_DEVICE}:${VIDEO_DEVICE}"
